server:
  port: 8099

spring:
  application:
    name: app_ac
  jackson:
    default-property-inclusion: non-null
    #property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:postgresql://localhost:5432/ac
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB



#    url: jdbc:postgresql://ep-noisy-breeze-ae621wd2-pooler.c-2.us-east-2.aws.neon.tech:5432/neondb?sslmode=require
#    username: neondb_owner
#    password: npg_zPtSy4jL7KqR

#    url: jdbc:postgresql://localhost:5432/ac
#    username: postgres
#    password: 12345