package com.asesoria.contable.app_ac.utils.enums;

public enum TipoAlertaCliente {
    DECLARACION_EN_PROCESO,
    DECLARACION_POR_VENCER,
    OBLIGACION_POR_VENCER,
    DECLARACION_VENCIDA,
    OBLIGACION_VENCIDA,
    NUEVA_OBLIGACION,
    DECLARACION_COMPLETADA,
    OBLIGACION_RESUELTA,
    PAGO_EN_PROCESO,
    PAGO_RECHAZADO,
    PAGO_ACEPTADO,
    PAGO_VALIDADO
}
